### ISSUE TITLE
Provide meaningful error message if ListenAndServe fails

### ISSUE THREAD

**Issue by breml** [okta/samples-golang#19]
If `ListenAndServe` fails, because e.g. the port is already in use, this example fails silently.

I suggest to replace in `main()`

```Go
http.ListenAndServe("localhost:8080", nil)
```

with

```Go
err := http.ListenAndServe("localhost:8080", nil)
if err != nil {
	log.Printf("Unable to start HTTP server: %s", err)
	os.Exit(1)
}
```

I am happy to provide a PR, but I am unsure if signing the CLA is necessary for this.

**Comment by bretterer** [comment]
Thanks for the feedback here.  I have implemented some error handling to report if the server failed to start.. This will be merged with #36
