### ISSUE TITLE
Resolve caching issue of /login

### ISSUE THREAD

**Issue by breml** [okta/samples-golang#20]
Instead of #10 or #13, the caching of `/login` could be resolved as well by adding a `Cache-Control` HTTP header.

Therefore I suggest to add

```Go
w.Header().Add("Cache-Control", "no-cache")
```

in `func LoginHandler`.

**Comment by bretterer** [comment]
Thanks for the info here.  We have updated code to include #10 and #13, but have also included your suggestion here.
