### ISSUE TITLE
Print message to console when server has been started

### ISSUE THREAD

**Issue by haishengwu-okta** [okta/samples-golang#25]
Today when run `go run main.go`, server got started without noticing user. 
I was assuming it will hence wait very long time and wonder if it got stuck but actually it started at `http://localhost:8080`

cc @bretterer

**Comment by bretterer** [comment]
Thanks @haishengwu-okta for the feedback.  We will add this to our list of things to take a look at. I think it would be a good idea to report that the server is running and on which port.

@bogdanprodan-okta is this something that is possible with the way these samples are currently running?

**Comment by bretterer** [comment]
After looking into this today, I realize that `ListenAndServe` is a blocking call, meaning after this, there is nothing that I can output to the console.  

I have added a "server starting ..." message at the start before starting the server so there is a little bit of feedback

**Comment by bretterer** [comment]
This has been resolved with #36

**Comment by haishengwu-okta** [comment]
Great! Thanks @bretterer !!
