### ISSUE TITLE
panic server jwt-verifier

### ISSUE THREAD

**Issue by felixn-unity** [okta/samples-golang#30]
Hi

I am not sure what is going on, I cloned the latest repos and added ENV variable, and when I click the "login" I am sent to okta to verify it credentials, but when it returns I get this dump:

```
2020/12/05 01:49:18 http2: panic serving 10.0.0.224:52491: interface conversion: interface {} is nil, not string
goroutine 63 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000288078, 0xc0000bdf8e, 0xc000102f00)
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/h2_bundle.go:5713 +0x16b
panic(0x1431f40, 0xc000244e70)
	/usr/local/Cellar/go/1.14.6/libexec/src/runtime/panic.go:969 +0x166
github.com/okta/okta-jwt-verifier-golang.(*JwtVerifier).decodeJwt(0xc0000bdb38, 0xc000374000, 0x411, 0x14a2801, 0x0, 0x0, 0x0)
	/Users/felixn/go/src/github.com/okta/okta-jwt-verifier-golang/jwtverifier.go:132 +0x1e4
github.com/okta/okta-jwt-verifier-golang.(*JwtVerifier).VerifyIdToken(0xc0000bdb38, 0xc000374000, 0x411, 0x185b840, 0xc000354ab8, 0x0)
	/Users/felixn/go/src/github.com/okta/okta-jwt-verifier-golang/jwtverifier.go:147 +0x9a
main.verifyToken(0xc000374000, 0x411, 0x14b05d1, 0x1f, 0xc0003680a0)
	/Users/felixn/git/iit-applications/it/auth-okta-paloalto/test/samples-golang/okta-hosted-login/main.go:209 +0x1d6
main.AuthCodeCallbackHandler(0x1549a40, 0xc000288078, 0xc000298c00)
	/Users/felixn/git/iit-applications/it/auth-okta-paloalto/test/samples-golang/okta-hosted-login/main.go:92 +0x22c
net/http.HandlerFunc.ServeHTTP(0x14c4c40, 0x1549a40, 0xc000288078, 0xc000298c00)
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x182fe40, 0x1549a40, 0xc000288078, 0xc000298c00)
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc0002a0000, 0x1549a40, 0xc000288078, 0xc000298c00)
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/server.go:2836 +0xa3
net/http.initALPNRequest.ServeHTTP(0x154ac80, 0xc0001a82d0, 0xc000182e00, 0xc0002a0000, 0x1549a40, 0xc000288078, 0xc000298c00)
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/server.go:3410 +0x8d
net/http.(*http2serverConn).runHandler(0xc000102f00, 0xc000288078, 0xc000298c00, 0xc000281820)
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
	/usr/local/Cellar/go/1.14.6/libexec/src/net/http/h2_bundle.go:5454 +0x4e1
token is not valid: you must provide a jwt to verify
```

I am sure this did not happen when using my app created with Okta developer/test account.

Any clues what could be wrong?

Thanks
Felix

**Comment by bretterer** [comment]
Could you tell me which sample you are using here?  it appears `okta-hosted-login`.

Did you add your env variables to `.env` or `.env.dist`?  The correct location is `.env`

**Comment by felixn-unity** [comment]
Hi 

I was using the golang library and I had to work with the node js to get it to work :(

I can try again, because would really like to the the golang library instead

Thanks
Felix

**Comment by felixn-unity** [comment]
Just did a fresh pull from https://github.com/okta/samples-golang/tree/master/okta-hosted-login

and tested it all looks good until the call-back runs I get this :

"token is not valid: you must provide a jwt to verify"

Thanks

**Comment by bretterer** [comment]
@felixn-unity I just did a pull of our sample, and was successful with the login.

Things to confirm:
1. Client ID and Client Secret are correct. These can be provided in the system environment variables, or within the `.env` file in the sample.
2. Your issuer is the correct URL.  This should look like `https://{yourOktaDomain}/oauth2/default`. This can be found in your Authorizaiton Servers list in the Okta dashboard.


Please let me know if this helps.

**Comment by felixn-unity** [comment]
Hi

On our production Okta we don't have the default Identity Provider, so -> 

export ISSUER=https://xxxx.okta.com/oauth2

Thanks
Felix

**Comment by bretterer** [comment]
Ah, That seems to be the issue.  We are not able to validate tokens locally, which is what these samples do when using the Okta issuer.  You will have to have access to custom authorization servers in order for this to work as expected.

For your org, you can reach out to developers@okta.com for more information around this and how to get you unblocked.

If there are any other concerns you have, please reply to this issue to re-open it.

**Comment by felixn-unity** [comment]
Ok, but the node.js example works just fine, is there a way to get the golang sample to work the same way?

**Comment by felixn-unity** [comment]
@bretterer any feedback on node.js works?

**Comment by bretterer** [comment]
I don't have an answer just yet.   I should have something by tomorrow

**Comment by felixn-unity** [comment]
Thank you so much :)

**Comment by bretterer** [comment]
I am not sure how the node.js example is working. The Golang Sample is working as we expect. 

If you can provide the steps you used for the node.js example that would allow me to reproduce this, I can dig into it further. However, the use of the Okta organization authorization server is not recommended and should not be used for these samples.

**Comment by felixn-unity** [comment]
I just cloned the node.js example and supplied these variables:

var ISSUER = 'https://xxxx.okta.com';
var CLIENT_ID = 
var CLIENT_SECRET = 
var CALLBACK_URL = 

I modified code to do some redirect and show that user is authenticated

And that works just fine

**Comment by bretterer** [comment]
Can you expand on which node.js sample you are talking about? 

https://github.com/okta?q=samples-js&type=&language=

**Comment by felixn-unity** [comment]
https://github.com/okta/okta-oidc-js/tree/master/packages/oidc-middleware

**Comment by felixn-unity** [comment]
Let me know if I should try/change anything

**Comment by bogdanprodan-okta** [comment]
I think the problem is in this function of the [okta-jwt-verifier-golang](https://github.com/okta/okta-jwt-verifier-golang/blob/develop/jwtverifier.go#L132) library:
```
func (j *JwtVerifier) decodeJwt(jwt string) (interface{}, error) {
	metaData, err := j.getMetaData()
	if err != nil {
		return nil, err
	}

	resp, err := j.Adaptor.Decode(jwt, metaData["jwks_uri"].(string)) // <----- this is causing panic in the code

	if err != nil {
		return nil, fmt.Errorf("could not decode token: %s", err.Error())
	}

	return resp, nil
}
```

I think we should add something like this to prevent code from panicing:
```
jwksURI, ok := metaData["jwks_uri"].(string)
if !ok {
     return nil, fmt.Errorf("can not decode token: missing 'jwks_uri' from metadata")
}
```

**Comment by bogdanprodan-okta** [comment]
Created PR for this panic: https://github.com/okta/okta-jwt-verifier-golang/pull/65
